### ISSUE TITLE
Free url throws 500 Server Error on first request

### ISSUE THREAD

**Issue by eppfel** [hackmdio/hackmd#344]
So, i enabled `allowfreeurl` in the configs and it works 🎉 , but sadly, only after reload.

First request to an new url `/wtf500`:

```log
2017-02-06 23:50:02.729305500 2017-02-06T22:50:02.729Z - info: deserializeUser: [***removed***]
2017-02-06 23:50:02.795568500 2017-02-06T22:50:02.793Z - error:  TypeError: Cannot read property 'length' of undefined
2017-02-06 23:50:02.795571500     at Model.<anonymous> (/home/eppcloud/hackmd/lib/models/revision.js:240:49)
2017-02-06 23:50:02.795573500     at Model.tryCatcher (/home/eppcloud/hackmd/node_modules/bluebird/js/release/util.js:16:23)
2017-02-06 23:50:02.795574500     at Promise._settlePromiseFromHandler (/home/eppcloud/hackmd/node_modules/bluebird/js/release/promise.js:510:31)
2017-02-06 23:50:02.795575500     at Promise._settlePromise (/home/eppcloud/hackmd/node_modules/bluebird/js/release/promise.js:567:18)
2017-02-06 23:50:02.795650500     at Promise._settlePromise0 (/home/eppcloud/hackmd/node_modules/bluebird/js/release/promise.js:612:10)
2017-02-06 23:50:02.795651500     at Promise._settlePromises (/home/eppcloud/hackmd/node_modules/bluebird/js/release/promise.js:691:18)
2017-02-06 23:50:02.795652500     at Async._drainQueue (/home/eppcloud/hackmd/node_modules/bluebird/js/release/async.js:133:16)
2017-02-06 23:50:02.795695500     at Async._drainQueues (/home/eppcloud/hackmd/node_modules/bluebird/js/release/async.js:143:10)
2017-02-06 23:50:02.795697500     at Immediate.Async.drainQueues (/home/eppcloud/hackmd/node_modules/bluebird/js/release/async.js:17:14)
2017-02-06 23:50:02.795698500     at runCallback (timers.js:637:20)
2017-02-06 23:50:02.795741500     at tryOnImmediate (timers.js:610:5)
2017-02-06 23:50:02.795742500     at processImmediate [as _immediateCallback] (timers.js:582:5)
2017-02-06 23:50:02.815941500 2017-02-06T22:50:02.815Z - info: ::ffff:127.0.0.1 - - [06/Feb/2017:22:50:02 +0000] "GET /wtf500 HTTP/1.1" 500 - "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"
2017-02-06 23:50:02.815945500 
```

Second request:

```
2017-02-06 23:50:42.474728500 2017-02-06T22:50:42.474Z - info: deserializeUser: [***removed***]
2017-02-06 23:50:42.508403500 2017-02-06T22:50:42.508Z - info: ::ffff:127.0.0.1 - - [06/Feb/2017:22:50:42 +0000] "GET /wtf500 HTTP/1.1" 200 - "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"
2017-02-06 23:50:42.508408500 
2017-02-06 23:50:43.627138500 2017-02-06T22:50:43.627Z - info: deserializeUser: [***removed***]
2017-02-06 23:50:44.035999500 2017-02-06T22:50:44.035Z - info: ::ffff:127.0.0.1 - - [06/Feb/2017:22:50:44 +0000] "GET /favicon.png HTTP/1.1" 200 725 "https://example.org/wtf500" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"
2017-02-06 23:50:44.036002500 
2017-02-06 23:50:44.804935500 2017-02-06T22:50:44.804Z - info: deserializeUser: [***removed***]
2017-02-06 23:50:44.819266500 2017-02-06T22:50:44.819Z - info: ::ffff:127.0.0.1 - - [06/Feb/2017:22:50:44 +0000] "GET /me HTTP/1.1" 304 - "https://example.org/wtf500" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"
2017-02-06 23:50:44.819269500 
```
 The server is on CentOs and node v6.9.1.

My config is:

```json

    "production": {
        "domain": "***removed***",
        "port": "61081",
        "debug": false,
        "db": {
            "username": "eppcloud",
            "password": "***removed***",
            "database": "eppcloud_hackmd",
            "host": "localhost",
            "port": "3306",
            "dialect": "mysql"
        },
	"github": {
            "clientID": "***removed***",
            "clientSecret": "***removed***"
        },
	"protocolusessl": true,
        "email": true,
        "allowemailregister": true,
        "allowfreeurl": true
    }
```

I used hackmd for a presentation the first time. It is such an amazing tool. Keep up that awesome work!

**Comment by jackycute** [comment]
Thanks @eppfel !

What's your hackmd version?
It seems like this is an old bug which solved in b1ec3ba748dc7b58015e97448958e78b512f6df0

**Comment by eppfel** [comment]
Sry, I forgot I'm on v0.5.0, so it should be solved by this...

**Comment by jackycute** [comment]
I think it should be done.
Please reopen this issue if this still bring up in 0.6.0.
