### ISSUE TITLE
Docker container does not execute DB setup

### ISSUE THREAD

**Issue by dns2utf8** [hackmdio/hackmd#366]
Hi all

I tested hackmd on my server (debian 8 with latest docker) last week and it worked like a charm.
Today I was unable to get it up and running on my other system (arch linux with latest patches).
I used the same docker-compose.yml but on arch, the DB times out the first time and the tables are not setup.

Regards

**Comment by jackycute** [comment]
Hi @dns2utf8 
Please paste you logs or we could figure out what's happened.
BTW, I would prefer this issue open in hackmdio/docker-hackmd instead of here.
Thanks.

**Comment by dns2utf8** [comment]
The issues in `docker-hackmd` are disabled.

Here is the log:
```
t
Creating hackmd_hackmdPostgres_1
Creating hackmd_hackmd_1
Attaching to hackmd_hackmdPostgres_1, hackmd_hackmd_1
hackmdPostgres_1  | The files belonging to this database system will be owned by user "postgres".
hackmdPostgres_1  | This user must also own the server process.
hackmdPostgres_1  | 
hackmdPostgres_1  | The database cluster will be initialized with locale "en_US.utf8".
hackmdPostgres_1  | The default database encoding has accordingly been set to "UTF8".
hackmdPostgres_1  | The default text search configuration will be set to "english".
hackmdPostgres_1  | 
hackmdPostgres_1  | Data page checksums are disabled.
hackmdPostgres_1  | 
hackmdPostgres_1  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
hackmdPostgres_1  | creating subdirectories ... ok
hackmdPostgres_1  | selecting default max_connections ... 100
hackmdPostgres_1  | selecting default shared_buffers ... 128MB
hackmdPostgres_1  | selecting dynamic shared memory implementation ... posix
hackmdPostgres_1  | creating configuration files ... ok
hackmdPostgres_1  | running bootstrap script ... ok
hackmd_1          | 
hackmd_1          | Sequelize [Node: 6.9.4, CLI: 2.5.1, ORM: 3.29.0]
hackmd_1          | 
hackmdPostgres_1  | performing post-bootstrap initialization ... ok
hackmd_1          | Parsed url postgres://hackmd:*****@hackmdPostgres:5432/hackmd
hackmd_1          | Unable to connect to database: SequelizeConnectionRefusedError: connect ECONNREFUSED 172.17.0.2:5432
hackmd_1          | Unhandled rejection SequelizeConnectionRefusedError: connect ECONNREFUSED 172.17.0.2:5432
hackmd_1          |     at /hackmd/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:98:20
hackmd_1          |     at Connection.<anonymous> (/hackmd/node_modules/pg/lib/client.js:185:5)
hackmd_1          |     at emitOne (events.js:96:13)
hackmd_1          |     at Connection.emit (events.js:188:7)
hackmd_1          |     at Socket.<anonymous> (/hackmd/node_modules/pg/lib/connection.js:71:10)
hackmd_1          |     at emitOne (events.js:96:13)
hackmd_1          |     at Socket.emit (events.js:188:7)
hackmd_1          |     at emitErrorNT (net.js:1278:8)
hackmd_1          |     at _combinedTickCallback (internal/process/next_tick.js:74:11)
hackmd_1          |     at process._tickCallback (internal/process/next_tick.js:98:9)
hackmdPostgres_1  | syncing data to disk ... ok
hackmdPostgres_1  | 
hackmdPostgres_1  | Success. You can now start the database server using:
hackmdPostgres_1  | 
hackmdPostgres_1  |     pg_ctl -D /var/lib/postgresql/data -l logfile start
hackmdPostgres_1  | 
hackmdPostgres_1  | 
hackmdPostgres_1  | WARNING: enabling "trust" authentication for local connections
hackmdPostgres_1  | You can change this by editing pg_hba.conf or using the option -A, or
hackmdPostgres_1  | --auth-local and --auth-host, the next time you run initdb.
hackmdPostgres_1  | waiting for server to start....LOG:  database system was shut down at 2017-02-21 13:22:05 UTC
hackmdPostgres_1  | LOG:  MultiXact member wraparound protections are now enabled
hackmdPostgres_1  | LOG:  autovacuum launcher started
hackmdPostgres_1  | LOG:  database system is ready to accept connections
hackmdPostgres_1  |  done
hackmdPostgres_1  | server started
hackmdPostgres_1  | CREATE DATABASE
hackmdPostgres_1  | 
hackmdPostgres_1  | CREATE ROLE
hackmdPostgres_1  | 
hackmdPostgres_1  | 
hackmdPostgres_1  | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
hackmdPostgres_1  | 
hackmdPostgres_1  | LOG:  received fast shutdown request
hackmdPostgres_1  | LOG:  aborting any active transactions
hackmdPostgres_1  | waiting for server to shut down....LOG:  autovacuum launcher shutting down
hackmdPostgres_1  | LOG:  shutting down
hackmdPostgres_1  | LOG:  database system is shut down
hackmdPostgres_1  |  done
hackmdPostgres_1  | server stopped
hackmdPostgres_1  | 
hackmdPostgres_1  | PostgreSQL init process complete; ready for start up.
hackmdPostgres_1  | 
hackmdPostgres_1  | LOG:  database system was shut down at 2017-02-21 13:22:34 UTC
hackmdPostgres_1  | LOG:  MultiXact member wraparound protections are now enabled
hackmdPostgres_1  | LOG:  autovacuum launcher started
hackmdPostgres_1  | LOG:  database system is ready to accept connections
```
after that there is no connection to nodejs available.
Then I kill the container and launch it again:
```
docker-compose up
Starting hackmd_hackmdPostgres_1
Starting hackmd_hackmd_1
Attaching to hackmd_hackmdPostgres_1, hackmd_hackmd_1
hackmdPostgres_1  | LOG:  database system was shut down at 2017-02-21 13:25:28 UTC
hackmdPostgres_1  | LOG:  MultiXact member wraparound protections are now enabled
hackmdPostgres_1  | LOG:  database system is ready to accept connections
hackmdPostgres_1  | LOG:  autovacuum launcher started
hackmd_1          | 
hackmd_1          | Sequelize [Node: 6.9.4, CLI: 2.5.1, ORM: 3.29.0]
hackmd_1          | 
hackmd_1          | Parsed url postgres://hackmd:*****@hackmdPostgres:5432/hackmd
hackmd_1          | == 20160515114000-user-add-tokens: migrating =======
hackmdPostgres_1  | ERROR:  relation "public.Users" does not exist
hackmdPostgres_1  | STATEMENT:  ALTER TABLE "public"."Users" ADD COLUMN "accessToken" VARCHAR(255);
hackmdPostgres_1  | ERROR:  relation "public.Users" does not exist
hackmdPostgres_1  | STATEMENT:  ALTER TABLE "public"."Users" ADD COLUMN "refreshToken" VARCHAR(255);
hackmd_1          | Unhandled rejection SequelizeDatabaseError: relation "public.Users" does not exist
hackmd_1          |     at Query.formatError (/hackmd/node_modules/sequelize/lib/dialects/postgres/query.js:357:14)
hackmd_1          |     at Query.<anonymous> (/hackmd/node_modules/sequelize/lib/dialects/postgres/query.js:88:19)
hackmd_1          |     at emitOne (events.js:96:13)
hackmd_1          |     at Query.emit (events.js:188:7)
hackmd_1          |     at Query.handleError (/hackmd/node_modules/pg/lib/query.js:131:8)
hackmd_1          |     at Connection.<anonymous> (/hackmd/node_modules/pg/lib/client.js:180:26)
hackmd_1          |     at emitOne (events.js:96:13)
hackmd_1          |     at Connection.emit (events.js:188:7)
hackmd_1          |     at Socket.<anonymous> (/hackmd/node_modules/pg/lib/connection.js:121:12)
hackmd_1          |     at emitOne (events.js:96:13)
hackmd_1          |     at Socket.emit (events.js:188:7)
hackmd_1          |     at readableAddChunk (_stream_readable.js:176:18)
hackmd_1          |     at Socket.Readable.push (_stream_readable.js:134:10)
hackmd_1          |     at TCP.onread (net.js:548:20)
hackmd_1          | Unhandled rejection SequelizeDatabaseError: relation "public.Users" does not exist
hackmd_1          |     at Query.formatError (/hackmd/node_modules/sequelize/lib/dialects/postgres/query.js:357:14)
hackmd_1          |     at Query.<anonymous> (/hackmd/node_modules/sequelize/lib/dialects/postgres/query.js:88:19)
hackmd_1          |     at emitOne (events.js:96:13)
hackmd_1          |     at Query.emit (events.js:188:7)
hackmd_1          |     at Query.handleError (/hackmd/node_modules/pg/lib/query.js:131:8)
hackmd_1          |     at Connection.<anonymous> (/hackmd/node_modules/pg/lib/client.js:180:26)
hackmd_1          |     at emitOne (events.js:96:13)
hackmd_1          |     at Connection.emit (events.js:188:7)
hackmd_1          |     at Socket.<anonymous> (/hackmd/node_modules/pg/lib/connection.js:121:12)
hackmd_1          |     at emitOne (events.js:96:13)
hackmd_1          |     at Socket.emit (events.js:188:7)
hackmd_1          |     at readableAddChunk (_stream_readable.js:176:18)
hackmd_1          |     at Socket.Readable.push (_stream_readable.js:134:10)
hackmd_1          |     at TCP.onread (net.js:548:20)
hackmd_1          | == 20160515114000-user-add-tokens: migrated (0.039s)
hackmd_1          | == 20160607060246-support-revision: migrating =======
hackmdPostgres_1  | ERROR:  relation "public.Notes" does not exist
hackmdPostgres_1  | STATEMENT:  ALTER TABLE "public"."Notes" ADD COLUMN "savedAt" TIMESTAMP WITH TIME ZONE;
hackmd_1          | Unhandled rejection SequelizeDatabaseError: relation "public.Notes" does not exist
hackmd_1          |     at Query.formatError (/hackmd/node_modules/sequelize/lib/dialects/postgres/query.js:357:14)
hackmd_1          |     at Query.<anonymous> (/hackmd/node_modules/sequelize/lib/dialects/postgres/query.js:88:19)
hackmd_1          |     at emitOne (events.js:96:13)
hackmd_1          |     at Query.emit (events.js:188:7)
hackmd_1          |     at Query.handleError (/hackmd/node_modules/pg/lib/query.js:131:8)
hackmd_1          |     at Connection.<anonymous> (/hackmd/node_modules/pg/lib/client.js:180:26)
hackmd_1          |     at emitOne (events.js:96:13)
hackmd_1          |     at Connection.emit (events.js:188:7)
hackmd_1          |     at Socket.<anonymous> (/hackmd/node_modules/pg/lib/connection.js:121:12)
hackmd_1          |     at emitOne (events.js:96:13)
hackmd_1          |     at Socket.emit (events.js:188:7)
hackmd_1          |     at readableAddChunk (_stream_readable.js:176:18)
hackmd_1          |     at Socket.Readable.push (_stream_readable.js:134:10)
hackmd_1          |     at TCP.onread (net.js:548:20)
hackmd_1          | == 20160607060246-support-revision: migrated (0.042s)
hackmd_1          | == 20160703062241-support-authorship: migrating =======
hackmdPostgres_1  | ERROR:  relation "public.Notes" does not exist
hackmdPostgres_1  | STATEMENT:  ALTER TABLE "public"."Notes" ADD COLUMN "authorship" TEXT;
hackmd_1          | Unhandled rejection SequelizeDatabaseError: relation "public.Notes" does not exist
hackmd_1          |     at Query.formatError (/hackmd/node_modules/sequelize/lib/dialects/postgres/query.js:357:14)
hackmd_1          |     at Query.<anonymous> (/hackmd/node_modules/sequelize/lib/dialects/postgres/query.js:88:19)
hackmd_1          |     at emitOne (events.js:96:13)
hackmd_1          |     at Query.emit (events.js:188:7)
hackmd_1          |     at Query.handleError (/hackmd/node_modules/pg/lib/query.js:131:8)
hackmd_1          |     at Connection.<anonymous> (/hackmd/node_modules/pg/lib/client.js:180:26)
hackmd_1          |     at emitOne (events.js:96:13)
hackmd_1          |     at Connection.emit (events.js:188:7)
hackmd_1          |     at Socket.<anonymous> (/hackmd/node_modules/pg/lib/connection.js:121:12)
hackmd_1          |     at emitOne (events.js:96:13)
hackmd_1          |     at Socket.emit (events.js:188:7)
hackmd_1          |     at readableAddChunk (_stream_readable.js:176:18)
hackmd_1          |     at Socket.Readable.push (_stream_readable.js:134:10)
hackmd_1          |     at TCP.onread (net.js:548:20)
hackmd_1          | == 20160703062241-support-authorship: migrated (0.050s)
hackmd_1          | == 20161009040430-support-delete-note: migrating =======
hackmdPostgres_1  | ERROR:  relation "public.Notes" does not exist
hackmdPostgres_1  | STATEMENT:  ALTER TABLE "public"."Notes" ADD COLUMN "deletedAt" TIMESTAMP WITH TIME ZONE;
hackmd_1          | Unhandled rejection SequelizeDatabaseError: relation "public.Notes" does not exist
hackmd_1          |     at Query.formatError (/hackmd/node_modules/sequelize/lib/dialects/postgres/query.js:357:14)
hackmd_1          |     at Query.<anonymous> (/hackmd/node_modules/sequelize/lib/dialects/postgres/query.js:88:19)
hackmd_1          |     at emitOne (events.js:96:13)
hackmd_1          |     at Query.emit (events.js:188:7)
hackmd_1          |     at Query.handleError (/hackmd/node_modules/pg/lib/query.js:131:8)
hackmd_1          |     at Connection.<anonymous> (/hackmd/node_modules/pg/lib/client.js:180:26)
hackmd_1          |     at emitOne (events.js:96:13)
hackmd_1          |     at Connection.emit (events.js:188:7)
hackmd_1          |     at Socket.<anonymous> (/hackmd/node_modules/pg/lib/connection.js:121:12)
hackmd_1          |     at emitOne (events.js:96:13)
hackmd_1          |     at Socket.emit (events.js:188:7)
hackmd_1          |     at readableAddChunk (_stream_readable.js:176:18)
hackmd_1          |     at Socket.Readable.push (_stream_readable.js:134:10)
hackmd_1          |     at TCP.onread (net.js:548:20)
hackmd_1          | == 20161009040430-support-delete-note: migrated (0.034s)
hackmd_1          | == 20161201050312-support-email-signin: migrating =======
hackmdPostgres_1  | ERROR:  relation "public.Users" does not exist
hackmdPostgres_1  | STATEMENT:  ALTER TABLE "public"."Users" ADD COLUMN "email" TEXT;
hackmdPostgres_1  | ERROR:  relation "public.Users" does not exist
hackmdPostgres_1  | STATEMENT:  ALTER TABLE "public"."Users" ADD COLUMN "password" TEXT;
hackmd_1          | Unhandled rejection SequelizeDatabaseError: relation "public.Users" does not exist
hackmd_1          |     at Query.formatError (/hackmd/node_modules/sequelize/lib/dialects/postgres/query.js:357:14)
hackmd_1          |     at Query.<anonymous> (/hackmd/node_modules/sequelize/lib/dialects/postgres/query.js:88:19)
hackmd_1          |     at emitOne (events.js:96:13)
hackmd_1          |     at Query.emit (events.js:188:7)
hackmd_1          |     at Query.handleError (/hackmd/node_modules/pg/lib/query.js:131:8)
hackmd_1          |     at Connection.<anonymous> (/hackmd/node_modules/pg/lib/client.js:180:26)
hackmd_1          |     at emitOne (events.js:96:13)
hackmd_1          |     at Connection.emit (events.js:188:7)
hackmd_1          |     at Socket.<anonymous> (/hackmd/node_modules/pg/lib/connection.js:121:12)
hackmd_1          |     at emitOne (events.js:96:13)
hackmd_1          |     at Socket.emit (events.js:188:7)
hackmd_1          |     at readableAddChunk (_stream_readable.js:176:18)
hackmd_1          |     at Socket.Readable.push (_stream_readable.js:134:10)
hackmd_1          |     at TCP.onread (net.js:548:20)
hackmd_1          | Unhandled rejection SequelizeDatabaseError: relation "public.Users" does not exist
hackmd_1          |     at Query.formatError (/hackmd/node_modules/sequelize/lib/dialects/postgres/query.js:357:14)
hackmd_1          |     at Query.<anonymous> (/hackmd/node_modules/sequelize/lib/dialects/postgres/query.js:88:19)
hackmd_1          |     at emitOne (events.js:96:13)
hackmd_1          |     at Query.emit (events.js:188:7)
hackmd_1          |     at Query.handleError (/hackmd/node_modules/pg/lib/query.js:131:8)
hackmd_1          |     at Connection.<anonymous> (/hackmd/node_modules/pg/lib/client.js:180:26)
hackmd_1          |     at emitOne (events.js:96:13)
hackmd_1          |     at Connection.emit (events.js:188:7)
hackmd_1          |     at Socket.<anonymous> (/hackmd/node_modules/pg/lib/connection.js:121:12)
hackmd_1          |     at emitOne (events.js:96:13)
hackmd_1          |     at Socket.emit (events.js:188:7)
hackmd_1          |     at readableAddChunk (_stream_readable.js:176:18)
hackmd_1          |     at Socket.Readable.push (_stream_readable.js:134:10)
hackmd_1          |     at TCP.onread (net.js:548:20)
hackmd_1          | == 20161201050312-support-email-signin: migrated (0.036s)
hackmd_1          | 2017-02-21T13:26:46.523Z - info: HTTP Server listening at port 3000
```

**Comment by jackycute** [comment]
I'm sorry, not noticing the issue is disabled in there.
Just turned it on.

**Comment by jackycute** [comment]
Hey @dns2utf8 
First please check if your docker, docker-machine and docker-compose (docker-toolbox) are all up-to-date.
And delete both `hackmd_hackmdPostgres_1` and `hackmd_hackmd_1` containers then try again.
According to the logs, I think the DB just failed to init and create tables.

**Comment by dns2utf8** [comment]
I have the latest updates of everything. I deleted everything but I gave me the same result:

```bash
$ docker rm hackmd_hackmd_1 hackmd_hackmdPostgres_1 
hackmd_hackmd_1
hackmd_hackmdPostgres_1
$ docker-compose up
Creating hackmd_hackmdPostgres_1
Creating hackmd_hackmd_1
Attaching to hackmd_hackmdPostgres_1, hackmd_hackmd_1
hackmdPostgres_1  | The files belonging to this database system will be owned by user "postgres".
hackmdPostgres_1  | This user must also own the server process.
hackmdPostgres_1  | 
hackmdPostgres_1  | The database cluster will be initialized with locale "en_US.utf8".
hackmdPostgres_1  | The default database encoding has accordingly been set to "UTF8".
hackmdPostgres_1  | The default text search configuration will be set to "english".
hackmdPostgres_1  | 
hackmdPostgres_1  | Data page checksums are disabled.
hackmdPostgres_1  | 
hackmdPostgres_1  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
hackmdPostgres_1  | creating subdirectories ... ok
hackmdPostgres_1  | selecting default max_connections ... 100
hackmdPostgres_1  | selecting default shared_buffers ... 128MB
hackmdPostgres_1  | selecting dynamic shared memory implementation ... posix
hackmdPostgres_1  | creating configuration files ... ok
hackmdPostgres_1  | running bootstrap script ... ok
hackmd_1          | 
hackmd_1          | Sequelize [Node: 6.9.2, CLI: 2.5.1, ORM: 3.28.0]
hackmd_1          | 
hackmdPostgres_1  | performing post-bootstrap initialization ... ok
hackmd_1          | Parsed url postgres://hackmd:*****@hackmdPostgres:5432/hackmd
hackmd_1          | Unable to connect to database: SequelizeConnectionRefusedError: connect ECONNREFUSED 172.17.0.2:5432
hackmd_1          | Unhandled rejection SequelizeConnectionRefusedError: connect ECONNREFUSED 172.17.0.2:5432
hackmd_1          |     at /hackmd/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:98:20
hackmd_1          |     at Connection.<anonymous> (/hackmd/node_modules/pg/lib/client.js:185:5)
hackmd_1          |     at emitOne (events.js:96:13)
hackmd_1          |     at Connection.emit (events.js:188:7)
hackmd_1          |     at Socket.<anonymous> (/hackmd/node_modules/pg/lib/connection.js:71:10)
hackmd_1          |     at emitOne (events.js:96:13)
hackmd_1          |     at Socket.emit (events.js:188:7)
hackmd_1          |     at emitErrorNT (net.js:1278:8)
hackmd_1          |     at _combinedTickCallback (internal/process/next_tick.js:74:11)
hackmd_1          |     at process._tickCallback (internal/process/next_tick.js:98:9)
hackmdPostgres_1  | syncing data to disk ... ok
hackmdPostgres_1  | 
hackmdPostgres_1  | Success. You can now start the database server using:
hackmdPostgres_1  | 
hackmdPostgres_1  |     pg_ctl -D /var/lib/postgresql/data -l logfile start
hackmdPostgres_1  | 
hackmdPostgres_1  | 
```

I think the problem is the node container is way faster then the postgres container and misses the connect window.

**Comment by dns2utf8** [comment]
I was able to start it after running and deleting it 5 times over. The fifth time the db was fast enough and it worked with this `docker-compose.yml` file:
```
version: "2"
services:
  hackmdPostgres:
    image: postgres
    environment:
      - POSTGRES_USER=hackmd
      - POSTGRES_PASSWORD=hackmdpass
      - POSTGRES_DB=hackmd
  sleep:
    image: yyekhlef/sleep
  hackmd:
    image: hackmdio/hackmd:0.5.0
    environment:
      - POSTGRES_USER=hackmd
      - POSTGRES_PASSWORD=hackmdpass
    links:
      - hackmdPostgres
      - sleep
    ports:
      - "3000:3000"
    depends_on:
      #- "hackmdPostgres"
      - "sleep"
```

**Comment by jackycute** [comment]
OK, then I think we need to add a good startup-order instead of just sleep around.
https://docs.docker.com/compose/startup-order/

**Comment by jackycute** [comment]
@dns2utf8 because this might be a long work and not directly related to this repo.
Could we move to hackmdio/docker-hackmd?

**Comment by a60814billy** [comment]
Hi @dns2utf8 , 

We're add dockerize to prevent the issue.
please see "docker-hackmd" master branch.

But we find another problem:
postgreSQL didn't have any table schemas when first startup HackMD docker container.
that will cause sequelize migration fail. but this does not affect HackMD running.

maybe in the future, we'll implement auto migration mechanism to solve this problem.
