### ISSUE TITLE
deploy to heroku, error column accessToken

### ISSUE THREAD

**Issue by shawngraham** [hackmdio/hackmd#402]
Hi folks,
Great project. I tried your deploy to heroku, got the following error at the 'run scripts & deploy dynamos' stage. I'm not entirely clear on what I would do to resolve the error, so thought I'd report the log here in case it's useful for you.

```
[4mSequelize [Node: 7.7.4, CLI: 2.6.0, ORM: 3.30.2][24m

Parsed url postgres://svzcktbcqxwacj:*****@ec2-54-225-127-147.compute-1.amazonaws.com:5432/d70ce8f1fu29d0
== 20160515114000-user-add-tokens: migrating =======
{ SequelizeBaseError: column "accessToken" of relation "Users" already exists
    at Query.formatError (/app/node_modules/sequelize/lib/dialects/postgres/query.js:357:14)
    at Query.<anonymous> (/app/node_modules/sequelize/lib/dialects/postgres/query.js:88:19)
    at emitOne (events.js:96:13)
    at Query.emit (events.js:191:7)
    at Query.handleError (/app/node_modules/pg/lib/query.js:143:8)
    at Connection.<anonymous> (/app/node_modules/pg/lib/client.js:180:26)
    at emitOne (events.js:96:13)
    at Connection.emit (events.js:191:7)
    at Socket.<anonymous> (/app/node_modules/pg/lib/connection.js:136:12)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:563:20)
  name: 'SequelizeDatabaseError',
  message: 'column "accessToken" of relation "Users" already exists',
  parent: 
   { error: column "accessToken" of relation "Users" already exists
       at Connection.parseE (/app/node_modules/pg/lib/connection.js:569:11)
       at Connection.parseMessage (/app/node_modules/pg/lib/connection.js:396:17)
       at Socket.<anonymous> (/app/node_modules/pg/lib/connection.js:132:22)
       at emitOne (events.js:96:13)
       at Socket.emit (events.js:191:7)
       at readableAddChunk (_stream_readable.js:178:18)
       at Socket.Readable.push (_stream_readable.js:136:10)
       at TCP.onread (net.js:563:20)
     name: 'error',
     length: 135,
     severity: 'ERROR',
     code: '42701',
     detail: undefined,
     hint: undefined,
     position: undefined,
     internalPosition: undefined,
     internalQuery: undefined,
     where: undefined,
     schema: undefined,
     table: undefined,
     column: undefined,
     dataType: undefined,
     constraint: undefined,
     file: 'tablecmds.c',
     line: '5096',
     routine: 'check_for_column_name_collision',
     sql: 'ALTER TABLE "public"."Users" ADD COLUMN "accessToken" VARCHAR(255);' },
  original: 
   { error: column "accessToken" of relation "Users" already exists
       at Connection.parseE (/app/node_modules/pg/lib/connection.js:569:11)
       at Connection.parseMessage (/app/node_modules/pg/lib/connection.js:396:17)
       at Socket.<anonymous> (/app/node_modules/pg/lib/connection.js:132:22)
       at emitOne (events.js:96:13)
       at Socket.emit (events.js:191:7)
       at readableAddChunk (_stream_readable.js:178:18)
       at Socket.Readable.push (_stream_readable.js:136:10)
       at TCP.onread (net.js:563:20)
     name: 'error',
     length: 135,
     severity: 'ERROR',
     code: '42701',
     detail: undefined,
     hint: undefined,
     position: undefined,
     internalPosition: undefined,
     internalQuery: undefined,
     where: undefined,
     schema: undefined,
     table: undefined,
     column: undefined,
     dataType: undefined,
     constraint: undefined,
     file: 'tablecmds.c',
     line: '5096',
     routine: 'check_for_column_name_collision',
     sql: 'ALTER TABLE "public"."Users" ADD COLUMN "accessToken" VARCHAR(255);' },
  sql: 'ALTER TABLE "public"."Users" ADD COLUMN "accessToken" VARCHAR(255);' }

```

**Comment by a60814billy** [comment]
Hi @shawngraham ,
It seems you use master branch to deploy to heroku,
master branch is not stable now, you can change to v0.5.1 tag to deploy the release version.

![](https://i.imgur.com/cUHvEyg.png)

**Comment by shawngraham** [comment]
ah, brilliant. thank you!
