### ISSUE TITLE
Heroku deployment - deploy button causes error

### ISSUE THREAD

**Issue by VinzentE** [hackmdio/hackmd#418]
Hi there,

I was just trying to deploy it to heroku:
1. used the "button" (one click deploy) - but didn't work
2. just using **heroku create projectname**  => did deploy, but now not working ether.

Anyone has an exact step-by-step tutorial which I could follow? I think I am missing some point, but can not find the issue.

Would love to use the 2nd method as I think it will give me more flexibility on how to quickly change s.th. deploy it and test it.

And:
Any idea on how to make the app "serverless"? I'd love to add some add-ons, but more in a serverless environment with AWS or firebase ....

Really appreciate any ideas ... 

thanks!

--- 
log for error on heroku:
[4mSequelize [Node: 7.8.0, CLI: 2.6.0, ORM: 3.30.2][24m

Parsed url postgres://ctjxyfzpofotgd:***@ec2-23-21-96-159.compute-1.amazonaws.com:5432/det86i1phuhkhv
== 20150504155329-create-users: migrating =======
== 20150504155329-create-users: migrated (0.032s)
== 20150508114741-create-notes: migrating =======
== 20150508114741-create-notes: migrated (0.018s)
== 20150515125813-create-temp: migrating =======
== 20150515125813-create-temp: migrated (0.026s)
== 20150702001020-update-to-0_3_1: migrating =======
{ SequelizeBaseError: column "shortid" of relation "Notes" already exists
    at Query.formatError (/app/node_modules/sequelize/lib/dialects/postgres/query.js:357:14)
    at Query.<anonymous> (/app/node_modules/sequelize/lib/dialects/postgres/query.js:88:19)
    at emitOne (events.js:96:13)
    at Query.emit (events.js:191:7)
    at Query.handleError (/app/node_modules/pg/lib/query.js:143:8)
    at Connection.<anonymous> (/app/node_modules/pg/lib/client.js:180:26)
    at emitOne (events.js:96:13)
    at Connection.emit (events.js:191:7)
    at Socket.<anonymous> (/app/node_modules/pg/lib/connection.js:136:12)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:559:20)
  name: 'SequelizeDatabaseError',
  message: 'column "shortid" of relation "Notes" already exists',
  parent: 
   { error: column "shortid" of relation "Notes" already exists
       at Connection.parseE (/app/node_modules/pg/lib/connection.js:569:11)
       at Connection.parseMessage (/app/node_modules/pg/lib/connection.js:396:17)
       at Socket.<anonymous> (/app/node_modules/pg/lib/connection.js:132:22)
       at emitOne (events.js:96:13)
       at Socket.emit (events.js:191:7)
       at readableAddChunk (_stream_readable.js:178:18)
       at Socket.Readable.push (_stream_readable.js:136:10)
       at TCP.onread (net.js:559:20)
     name: 'error',
     length: 131,
     severity: 'ERROR',
     code: '42701',
     detail: undefined,
     hint: undefined,
     position: undefined,
     internalPosition: undefined,
     internalQuery: undefined,
     where: undefined,
     schema: undefined,
     table: undefined,
     column: undefined,
     dataType: undefined,
     constraint: undefined,
     file: 'tablecmds.c',
     line: '5097',
     routine: 'check_for_column_name_collision',
     sql: 'ALTER TABLE "public"."Notes" ADD COLUMN "shortid" VARCHAR(255) NOT NULL DEFAULT \'0000000000\';' },
  original: 
   { error: column "shortid" of relation "Notes" already exists
       at Connection.parseE (/app/node_modules/pg/lib/connection.js:569:11)
       at Connection.parseMessage (/app/node_modules/pg/lib/connection.js:396:17)
       at Socket.<anonymous> (/app/node_modules/pg/lib/connection.js:132:22)
       at emitOne (events.js:96:13)
       at Socket.emit (events.js:191:7)
       at readableAddChunk (_stream_readable.js:178:18)
       at Socket.Readable.push (_stream_readable.js:136:10)
       at TCP.onread (net.js:559:20)
     name: 'error',
     length: 131,
     severity: 'ERROR',
     code: '42701',
     detail: undefined,
     hint: undefined,
     position: undefined,
     internalPosition: undefined,
     internalQuery: undefined,
     where: undefined,
     schema: undefined,
     table: undefined,
     column: undefined,
     dataType: undefined,
     constraint: undefined,
     file: 'tablecmds.c',
     line: '5097',
     routine: 'check_for_column_name_collision',
     sql: 'ALTER TABLE "public"."Notes" ADD COLUMN "shortid" VARCHAR(255) NOT NULL DEFAULT \'0000000000\';' },
  sql: 'ALTER TABLE "public"."Notes" ADD COLUMN "shortid" VARCHAR(255) NOT NULL DEFAULT \'0000000000\';' }

**Comment by Yukaii** [comment]
Hi @VinzentE, since our master is under active development, something may be unstable now.

You can try deploy a stable version by the method in https://github.com/hackmdio/hackmd/issues/402#issuecomment-289195427. Thanks!

**Comment by SISheogorath** [comment]
Deploying version `0.5.1` and earlier possibly fail... See https://github.com/hackmdio/docker-hackmd/pull/14#issuecomment-293628055

(We should really consider to provide a branch which backports bugfixes to the latest release and/or split up Master and Dev branch)

**Comment by VinzentE** [comment]
Thanks! 
I agree - different branches might solve that. 
Important from my perspective would be that the heroku deploy "just works" - even if it not with the current (but eventually unstable) branch.

**Comment by Yukaii** [comment]
We resolved this issue in #450, close this now 😄
