### ISSUE TITLE
Error on bin/setup

### ISSUE THREAD

**Issue by tjcarroll11** [hackmdio/hackmd#464]
I'm trying to set up hackmd on my Mac, but when I run bin/setup, I keep getting the following error:

20773 verbose addRemoteGit caching git://github.com/adobe-webplatform/eve.git#eef80ed
20774 verbose addRemoteGit git://github.com/adobe-webplatform/eve.git#eef80ed is a repository hosted by github
20775 silly tryClone cloning git://github.com/adobe-webplatform/eve.git#eef80ed via git://github.com/adobe-webplatform/eve.git#eef80ed
20776 verbose tryClone git-github-com-adobe-webplatform-eve-git-eef80ed-3ede0067 not in flight; caching
20777 verbose correctMkdir /Users/tim.carroll/.npm/_git-remotes correctMkdir not in flight; initializing
20778 info git [ 'clone',
20778 info git   '--template=/Users/tim.carroll/.npm/_git-remotes/_templates',
20778 info git   '--mirror',
20778 info git   'git://github.com/adobe-webplatform/eve.git',
20778 info git   '/Users/tim.carroll/.npm/_git-remotes/git-github-com-adobe-webplatform-eve-git-eef80ed-3ede0067' ]
20779 error git clone --template=/Users/tim.carroll/.npm/_git-remotes/_templates --mirror git://github.com/adobe-webplatform/eve.git /Users/tim.carroll/.npm/_git-remotes/git-github-com-adobe-webplatform-eve-git-eef80ed-3ede0067: Cloning into bare repository '/Users/tim.carroll/.npm/_git-remotes/git-github-com-adobe-webplatform-eve-git-eef80ed-3ede0067'...
20779 error git clone --template=/Users/tim.carroll/.npm/_git-remotes/_templates --mirror git://github.com/adobe-webplatform/eve.git /Users/tim.carroll/.npm/_git-remotes/git-github-com-adobe-webplatform-eve-git-eef80ed-3ede0067: fatal: unable to connect to github.com:
20779 error git clone --template=/Users/tim.carroll/.npm/_git-remotes/_templates --mirror git://github.com/adobe-webplatform/eve.git /Users/tim.carroll/.npm/_git-remotes/git-github-com-adobe-webplatform-eve-git-eef80ed-3ede0067: github.com[0: 192.30.253.112]: errno=Operation timed out
20779 error git clone --template=/Users/tim.carroll/.npm/_git-remotes/_templates --mirror git://github.com/adobe-webplatform/eve.git /Users/tim.carroll/.npm/_git-remotes/git-github-com-adobe-webplatform-eve-git-eef80ed-3ede0067: github.com[1: 192.30.253.113]: errno=Operation timed out
20780 silly fetchPackageMetaData Error: Command failed: git clone --template=/Users/tim.carroll/.npm/_git-remotes/_templates --mirror git://github.com/adobe-webplatform/eve.git /Users/tim.carroll/.npm/_git-remotes/git-github-com-adobe-webplatform-eve-git-eef80ed-3ede0067
20780 silly fetchPackageMetaData Cloning into bare repository '/Users/tim.carroll/.npm/_git-remotes/git-github-com-adobe-webplatform-eve-git-eef80ed-3ede0067'...
20780 silly fetchPackageMetaData fatal: unable to connect to github.com:
20780 silly fetchPackageMetaData github.com[0: 192.30.253.112]: errno=Operation timed out
20780 silly fetchPackageMetaData github.com[1: 192.30.253.113]: errno=Operation timed out
20780 silly fetchPackageMetaData
20780 silly fetchPackageMetaData
20780 silly fetchPackageMetaData     at ChildProcess.exithandler (child_process.js:211:12)
20780 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
20780 silly fetchPackageMetaData     at ChildProcess.emit (events.js:191:7)
20780 silly fetchPackageMetaData     at maybeClose (internal/child_process.js:885:16)
20780 silly fetchPackageMetaData     at Socket.<anonymous> (internal/child_process.js:334:11)
20780 silly fetchPackageMetaData     at emitOne (events.js:96:13)
20780 silly fetchPackageMetaData     at Socket.emit (events.js:188:7)
20780 silly fetchPackageMetaData     at Pipe._handle.close [as _onclose] (net.js:501:12)
20780 silly fetchPackageMetaData  error for eve@git://github.com/adobe-webplatform/eve.git#eef80ed { Error: Command failed: git clone --template=/Users/tim.carroll/.npm/_git-remotes/_templates --mirror git://github.com/adobe-webplatform/eve.git /Users/tim.carroll/.npm/_git-remotes/git-github-com-adobe-webplatform-eve-git-eef80ed-3ede0067
20780 silly fetchPackageMetaData Cloning into bare repository '/Users/tim.carroll/.npm/_git-remotes/git-github-com-adobe-webplatform-eve-git-eef80ed-3ede0067'...
20780 silly fetchPackageMetaData fatal: unable to connect to github.com:
20780 silly fetchPackageMetaData github.com[0: 192.30.253.112]: errno=Operation timed out
20780 silly fetchPackageMetaData github.com[1: 192.30.253.113]: errno=Operation timed out
20780 silly fetchPackageMetaData
20780 silly fetchPackageMetaData
20780 silly fetchPackageMetaData     at ChildProcess.exithandler (child_process.js:211:12)
20780 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
20780 silly fetchPackageMetaData     at ChildProcess.emit (events.js:191:7)
20780 silly fetchPackageMetaData     at maybeClose (internal/child_process.js:885:16)
20780 silly fetchPackageMetaData     at Socket.<anonymous> (internal/child_process.js:334:11)
20780 silly fetchPackageMetaData     at emitOne (events.js:96:13)
20780 silly fetchPackageMetaData     at Socket.emit (events.js:188:7)
20780 silly fetchPackageMetaData     at Pipe._handle.close [as _onclose] (net.js:501:12)
20780 silly fetchPackageMetaData   killed: false,
20780 silly fetchPackageMetaData   code: 128,
20780 silly fetchPackageMetaData   signal: null,
20780 silly fetchPackageMetaData   cmd: 'git clone --template=/Users/tim.carroll/.npm/_git-remotes/_templates --mirror git://github.com/adobe-webplatform/eve.git /Users/tim.carroll/.npm/_git-remotes/git-github-com-adobe-webplatform-eve-git-eef80ed-3ede0067' }
20781 silly timing Tried to end timer that doesn't exist: stage:runTopLevelLifecycles
20782 silly install printInstalled
20783 verbose stack Error: Command failed: git clone --template=/Users/tim.carroll/.npm/_git-remotes/_templates --mirror git://github.com/adobe-webplatform/eve.git /Users/tim.carroll/.npm/_git-remotes/git-github-com-adobe-webplatform-eve-git-eef80ed-3ede0067
20783 verbose stack Cloning into bare repository '/Users/tim.carroll/.npm/_git-remotes/git-github-com-adobe-webplatform-eve-git-eef80ed-3ede0067'...
20783 verbose stack fatal: unable to connect to github.com:
20783 verbose stack github.com[0: 192.30.253.112]: errno=Operation timed out
20783 verbose stack github.com[1: 192.30.253.113]: errno=Operation timed out
20783 verbose stack
20783 verbose stack
20783 verbose stack     at ChildProcess.exithandler (child_process.js:211:12)
20783 verbose stack     at emitTwo (events.js:106:13)
20783 verbose stack     at ChildProcess.emit (events.js:191:7)
20783 verbose stack     at maybeClose (internal/child_process.js:885:16)
20783 verbose stack     at Socket.<anonymous> (internal/child_process.js:334:11)
20783 verbose stack     at emitOne (events.js:96:13)
20783 verbose stack     at Socket.emit (events.js:188:7)
20783 verbose stack     at Pipe._handle.close [as _onclose] (net.js:501:12)
20784 verbose cwd /Users/tim.carroll/repo/hackmd
20785 verbose Darwin 16.5.0
20786 verbose argv "/usr/local/Cellar/node/7.3.0/bin/node" "/usr/local/bin/npm" "install"
20787 verbose node v7.3.0
20788 verbose npm  v4.6.1
20789 error code 128
20790 error Command failed: git clone --template=/Users/tim.carroll/.npm/_git-remotes/_templates --mirror git://github.com/adobe-webplatform/eve.git /Users/tim.carroll/.npm/_git-remotes/git-github-com-adobe-webplatform-eve-git-eef80ed-3ede0067
20790 error Cloning into bare repository '/Users/tim.carroll/.npm/_git-remotes/git-github-com-adobe-webplatform-eve-git-eef80ed-3ede0067'...
20790 error fatal: unable to connect to github.com:
20790 error github.com[0: 192.30.253.112]: errno=Operation timed out
20790 error github.com[1: 192.30.253.113]: errno=Operation timed out
20791 verbose exit [ 1, true ]

I'm fairly confident that it isn't my connection, despite the cannot connect error.

**Comment by tjcarroll11** [comment]
Appeared to be a firewall thing or something. I was able to resolve the issue by changing my git settings to only use https: 

git config --global url."https://".insteadOf git://
