### ISSUE TITLE
Redeploying to heroku fails with "codemirror.min.js doesn't exist"

### ISSUE THREAD

**Issue by tomgoto** [hackmdio/hackmd#496]
Hello hackmd! 
Thank you for a great tool.
It really helps my productivity!

I'm using hackmd deployed to Heroku and 
found that I could successfully deploy to heroku from scratch ( using "Deploy to Heroku" button at README.md), but fails when re-deploying.

Here's the Build log.

```
-----> Building dependencies
  (snip)
       [4/4] Building fresh packages...
       $ bin/heroku
       
       > hackmd@0.5.1 build /tmp/build_52475d4c3ac96ee2f56b7547df230cb4/tomgoto-hackmdtestone-a2d1f96
       > webpack --config webpack.production.js --progress --colors --bail
       
 70% 16/16 b  0% compileError
       at /tmp/build_52475d4c3ac96ee2f56b7547df230cb4/tomgoto-hackmdtestone-a2d1f96/node_modules/webpack/lib/Compilation.js:229:38
       at onDoneResolving (/tmp/build_52475d4c3ac96ee2f56b7547df230cb4/tomgoto-hackmdtestone-a2d1f96/node_modules/webpack/lib/NormalModuleFactory.js:29:20)
       at /tmp/build_52475d4c3ac96ee2f56b7547df230cb4/tomgoto-hackmdtestone-a2d1f96/node_modules/webpack/lib/NormalModuleFactory.js:85:20
       at /tmp/build_52475d4c3ac96ee2f56b7547df230cb4/tomgoto-hackmdtestone-a2d1f96/node_modules/webpack/node_modules/async/lib/async.js:726:13
       at /tmp/build_52475d4c3ac96ee2f56b7547df230cb4/tomgoto-hackmdtestone-a2d1f96/node_modules/webpack/node_modules/async/lib/async.js:52:16
       at done (/tmp/build_52475d4c3ac96ee2f56b7547df230cb4/tomgoto-hackmdtestone-a2d1f96/node_modules/webpack/node_modules/async/lib/async.js:241:17)
       at /tmp/build_52475d4c3ac96ee2f56b7547df230cb4/tomgoto-hackmdtestone-a2d1f96/node_modules/webpack/node_modules/async/lib/async.js:44:16
       at /tmp/build_52475d4c3ac96ee2f56b7547df230cb4/tomgoto-hackmdtestone-a2d1f96/node_modules/webpack/node_modules/async/lib/async.js:723:17
       at /tmp/build_52475d4c3ac96ee2f56b7547df230cb4/tomgoto-hackmdtestone-a2d1f96/node_modules/webpack/node_modules/async/lib/async.js:167:37
       at /tmp/build_52475d4c3ac96ee2f56b7547df230cb4/tomgoto-hackmdtestone-a2d1f96/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:24:19
       at onResolved (/tmp/build_52475d4c3ac96ee2f56b7547df230cb4/tomgoto-hackmdtestone-a2d1f96/node_modules/enhanced-resolve/lib/Resolver.js:38:18)
       at innerCallback (/tmp/build_52475d4c3ac96ee2f56b7547df230cb4/tomgoto-hackmdtestone-a2d1f96/node_modules/enhanced-resolve/lib/Resolver.js:88:19)
       at loggingCallbackWrapper (/tmp/build_52475d4c3ac96ee2f56b7547df230cb4/tomgoto-hackmdtestone-a2d1f96/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
       at /tmp/build_52475d4c3ac96ee2f56b7547df230cb4/tomgoto-hackmdtestone-a2d1f96/node_modules/tapable/lib/Tapable.js:134:6
       at Resolver.<anonymous> (/tmp/build_52475d4c3ac96ee2f56b7547df230cb4/tomgoto-hackmdtestone-a2d1f96/node_modules/enhanced-resolve/lib/DirectoryDescriptionFileFieldAliasPlugin.js:75:26)
       at /tmp/build_52475d4c3ac96ee2f56b7547df230cb4/tomgoto-hackmdtestone-a2d1f96/node_modules/enhanced-resolve/lib/DirectoryDescriptionFileFieldAliasPlugin.js:52:26
       at Storage.finished (/tmp/build_52475d4c3ac96ee2f56b7547df230cb4/tomgoto-hackmdtestone-a2d1f96/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
       at /tmp/build_52475d4c3ac96ee2f56b7547df230cb4/tomgoto-hackmdtestone-a2d1f96/node_modules/graceful-fs/graceful-fs.js:78:16
       at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:503:3)
       resolve file
       /tmp/build_52475d4c3ac96ee2f56b7547df230cb4/tomgoto-hackmdtestone-a2d1f96/node_modules/codemirror/codemirror.min.js doesn't exist
       /tmp/build_52475d4c3ac96ee2f56b7547df230cb4/tomgoto-hackmdtestone-a2d1f96/node_modules/codemirror/codemirror.min.js.js doesn't exist
       resolve directory
       /tmp/build_52475d4c3ac96ee2f56b7547df230cb4/tomgoto-hackmdtestone-a2d1f96/node_modules/codemirror/codemirror.min.js doesn't exist (directory default file)
       /tmp/build_52475d4c3ac96ee2f56b7547df230cb4/tomgoto-hackmdtestone-a2d1f96/node_modules/codemirror/codemirror.min.js/package.json doesn't exist (directory description file)
 62% 759/864 buil       Starting to optimize CSS...
       Processing html.min.css...
       Processed html.min.css, before: 23230, after: 17622, ratio: 75.86%
 70% 1206/1206 build modulesnpm ERR! code ELIFECYCLE

```

Am I missing something?
I'll try several other methods and report them here.
Thank you.

**Comment by tomgoto** [comment]
Somehow above issue is gone.
I confirmed building works now, Thank you.
