### ISSUE TITLE
Google OAuth Broken

### ISSUE THREAD

**Issue by bert2002** [hackmdio/hackmd#582]
Hi,
just pulled master (53c2d0b) and configured Google OAuth for it and the Google callback call fails:

```
2017-10-12T09:58:03.803Z - info: ::ffff:10.0.0.2 - - [12/Oct/2017:09:58:03 +0000] "GET /auth/google HTTP/1.1" 302 0 "http://example.org/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36"

Error
    at /srv/example/hackmd/node_modules/passport-google-oauth20/lib/strategy.js:95:21
    at passBackControl (/srv/example/hackmd/node_modules/oauth/lib/oauth2.js:132:9)
    at IncomingMessage.<anonymous> (/srv/example/hackmd/node_modules/oauth/lib/oauth2.js:157:7)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
2017-10-12T09:58:06.660Z - info: ::ffff:10.0.0.2 - - [12/Oct/2017:09:58:06 +0000] "GET /auth/google/callback?code=CODE HTTP/1.1" 500 148 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36"
```
The config.json contains ClientID and clientSecret. If you need more information, please let me know.

Thanks

bert

**Comment by SISheogorath** [comment]
When I check the Example config.json there is also an API-key:

https://github.com/hackmdio/hackmd/blob/53c2d0b5ca5901c1d1cad819e2049b16fba18ea8/config.json.example#L47-L51

Did you set this, too?

**Comment by bert2002** [comment]
Hi @SISheogorath,
for testing purposes I added it and completely rebuilded it as well. Same 500 :( 
Normally they are two different things, apiKey and OAuth (when you ask Google).

Many Thanks

bert

**Comment by jackycute** [comment]
Hi @bert2002, I think you'll need to enable Google+ API.
refer to #259

**Comment by bert2002** [comment]
You are right @jackycute. Enabling the Google Plus API worked. Thanks.
