### ISSUE TITLE
SSL Segmentation fault

### ISSUE THREAD

**Issue by laysdra7265** [hackmdio/hackmd#642]
Encounter a strange problem
``` console

2017-12-02T06:09:58.446Z - info: deserializeUser: 07ff2df7-7423-4238-8b05-12a6b5c8137e
2017-12-02T06:09:58.466Z - info: ::ffff:127.0.0.1 - - [02/Dec/2017:06:09:58 +0000] "GET /history HTTP/1.0" 200 - "https://hackmd.dragcon.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36"

2017-12-02T06:09:59.911Z - info: deserializeUser: 07ff2df7-7423-4238-8b05-12a6b5c8137e
2017-12-02T06:09:59.973Z - info: ::ffff:127.0.0.1 - - [02/Dec/2017:06:09:59 +0000] "GET /MYJgDAnAhgLArGAtFOAzViYA5gDZljDCbBQRhZQAmcA7FbkA HTTP/1.0" 304 - "https://hackmd.dragcon.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36"

2017-12-02T06:10:02.164Z - info: deserializeUser: 07ff2df7-7423-4238-8b05-12a6b5c8137e
./start.sh: line 2: 21427 Segmentation fault      npm start
```
nginx might cause server crash,I not sure how to config it right.
Since add WS support for socketio to nginx will cause server crash and throw Segmentation fault.
Here is hackmd config and nginx config.
```json
{
    "test": {
        "db": {
            "dialect": "sqlite",
            "storage": ":memory:"
        }
    },
    "development": {
        "hsts": {
            "enable": false
        },
        "db": {
            "dialect": "sqlite",
            "storage": "./db.hackmd.sqlite"
        }
    },
    "production": {
        "domain": "hackmd.example.com",
		"urladdport":false,
		"port":3000,
		"usecdn":false,
		"alloworigin":[],
        "hsts": {
            "enable": true,
            "maxAgeSeconds": "31536000",
            "includeSubdomains": "true",
            "preload": "true"
        },
        "db": {
            "dialect": "sqlite",
            "storage": "./db.hackmd.sqlite"
        },
		"imageUploadType":"filesystem",
       "allowanonymous":false,
	   "allowfreeurl":false,
	   "defaultpermission":"limited",
	   "usessl":true,
	   "protocolusessl":true,
	   "sslkeypath":"./ssl/private.key",
	   "sslcertpath":"./ssl/certificate.crt",
	   "sslcapath":["./ssl/ca_bundle.crt"],
	   "dhparampath":"./ssl/dhparam.pem"
    }
}
```

```nginx
server
	{
		listen 443 ssl;
		server_name hackmd.example.com;
		ssl_certificate     /hackmd/ssl/certificate.crt;
		ssl_certificate_key /hackmd/ssl/private.key;
		ssl_dhparam			/hackmd/ssl/dhparam.pem;
		ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
		ssl_ciphers         HIGH:!aNULL:!MD5;
		
		location / {
			proxy_redirect off;
			proxy_set_header Host $http_host;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			
			proxy_pass https://127.0.0.1:3000;
			
			# enables WS support
			proxy_http_version 1.1;
			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Connection "upgrade";

			proxy_read_timeout 999999999;
		}
		
		
	}
```

**Comment by laysdra7265** [comment]
oh.... it looks the Earlier crash caused the database broken and caused the Segmentation fault.

**Comment by laysdra7265** [comment]
I don't know what is broken.I just found out that the connection is unstable,and the console is keep output 400 error response.And I try to add add WS support for socketio to nginx.I get 502 bad gateway and some error output:
```console
2017-12-02T04:47:30.975Z - error:  Error: Both operations have to have the same base length
    at ot.TextOperation.TextOperation.transform (/home/hackmd/lib/ot/text-operation.js:411:13)
    at ot.WrappedOperation.WrappedOperation.transform (/home/hackmd/lib/ot/wrapped-operation.js:66:16)
    at EditorSocketIOServer.ot.Server.Server.receiveOperation (/home/hackmd/lib/ot/server.js:29:19)
    at EditorSocketIOServer.onOperation (/home/hackmd/lib/ot/editor-socketio-server.js:107:33)
    at /home/hackmd/lib/ot/editor-socketio-server.js:51:22
    at EditorSocketIOServer.ifMayEdit [as mayWrite] (/home/hackmd/lib/realtime.js:652:10)
    at Socket.<anonymous> (/home/hackmd/lib/ot/editor-socketio-server.js:45:14)
    at emitThree (events.js:116:13)
    at Socket.emit (events.js:194:7)
    at /home/hackmd/node_modules/socket.io/lib/socket.js:503:12
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
2017-12-02T04:47:46.116Z - error:  Error: Both operations have to have the same base length
    at ot.TextOperation.TextOperation.transform (/home/hackmd/lib/ot/text-operation.js:411:13)
    at ot.WrappedOperation.WrappedOperation.transform (/home/hackmd/lib/ot/wrapped-operation.js:66:16)
    at EditorSocketIOServer.ot.Server.Server.receiveOperation (/home/hackmd/lib/ot/server.js:29:19)
    at EditorSocketIOServer.onOperation (/home/hackmd/lib/ot/editor-socketio-server.js:107:33)
    at /home/hackmd/lib/ot/editor-socketio-server.js:51:22
    at EditorSocketIOServer.ifMayEdit [as mayWrite] (/home/hackmd/lib/realtime.js:652:10)
    at Socket.<anonymous> (/home/hackmd/lib/ot/editor-socketio-server.js:45:14)
    at emitThree (events.js:116:13)
    at Socket.emit (events.js:194:7)
    at /home/hackmd/node_modules/socket.io/lib/socket.js:503:12
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
2017-12-02T04:47:46.117Z - error:  Error: Both operations have to have the same base length
    at ot.TextOperation.TextOperation.transform (/home/hackmd/lib/ot/text-operation.js:411:13)
    at ot.WrappedOperation.WrappedOperation.transform (/home/hackmd/lib/ot/wrapped-operation.js:66:16)
    at EditorSocketIOServer.ot.Server.Server.receiveOperation (/home/hackmd/lib/ot/server.js:29:19)
    at EditorSocketIOServer.onOperation (/home/hackmd/lib/ot/editor-socketio-server.js:107:33)
    at /home/hackmd/lib/ot/editor-socketio-server.js:51:22
    at EditorSocketIOServer.ifMayEdit [as mayWrite] (/home/hackmd/lib/realtime.js:652:10)
    at Socket.<anonymous> (/home/hackmd/lib/ot/editor-socketio-server.js:45:14)
    at emitThree (events.js:116:13)
    at Socket.emit (events.js:194:7)
    at /home/hackmd/node_modules/socket.io/lib/socket.js:503:12
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```
I try to fix the config several times, and I found the pm2 just keep restart server when socket.io request incoming. I guess there is something broken (I guess is database) and now it just simply throwing Segmentation fault without any error message even though I disabled the nginx.

**Comment by laysdra7265** [comment]
I use ` sqlite3 bak.db.hackmd.sqlite "pragma integrity_check"` and `sqlite3 bak.db.hackmd.sqlite "pragma quick_check"` to check.it looks fine to database.Try to restart vps,nothing change

**Comment by laysdra7265** [comment]
The database work fine on windows,I guess I need to resetup the environment again on my vps.

**Comment by laysdra7265** [comment]
When I turn off the ssl option,everything back to normally
That really strange,so is this some kind of bug about ssl and node?

**Comment by laysdra7265** [comment]
Ok I disable the ssl on hackmd
Use it only on reverse proxy with nginx,It finally work again
It might be issue with openssl or https with node on centos.

**Comment by ccoenen** [comment]
You can also disable SSL on hackmd and have nginx provide the encryption to the outside world. That's what I do with HackMD+Apache. My HackMD only runs on 127.0.0.1 and this is being proxied by apache.

**Comment by laysdra7265** [comment]
The strangely part, it didn't crash at the first time I setup the ssl on hackmd,until I change the config of nginx. That really made me confused.
