### ISSUE TITLE
ER_DATA_TOO_LONG Problems with MySql

### ISSUE THREAD

**Issue by ericma15** [hackmdio/hackmd#821]
```
2018-05-15T12:56:43.555Z - error: updater error SequelizeBaseError: ER_DATA_TOO_LONG: Data too long for column 'content' at row 1
    at Query.formatError (/var/www/md/node_modules/_sequelize@3.30.4@sequelize/lib/dialects/mysql/query.js:175:14)
    at Query._callback (/var/www/md/node_modules/_sequelize@3.30.4@sequelize/lib/dialects/mysql/query.js:49:21)
    at Query.Sequence.end (/var/www/md/node_modules/_mysql@2.15.0@mysql/lib/protocol/sequences/Sequence.js:88:24)
    at Query.ErrorPacket (/var/www/md/node_modules/_mysql@2.15.0@mysql/lib/protocol/sequences/Query.js:90:8)
    at Protocol._parsePacket (/var/www/md/node_modules/_mysql@2.15.0@mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/var/www/md/node_modules/_mysql@2.15.0@mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/var/www/md/node_modules/_mysql@2.15.0@mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/var/www/md/node_modules/_mysql@2.15.0@mysql/lib/Connection.js:103:28)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
    at Socket.Readable.push (_stream_readable.js:211:10)
    at TCP.onread (net.js:585:20)

```
This cause because hackmd  never delete history, so  "patch" and "content" in table Revisons can easily become too long.
mysql> desc Revisions;
```
+-------------+------------+------+-----+---------+-------+
| Field       | Type       | Null | Key | Default | Extra |
+-------------+------------+------+-----+---------+-------+
| id          | char(36)   | NO   | PRI | NULL    |       |
| patch       | mediumtext | YES  |     | NULL    |       |
| lastContent | text       | YES  |     | NULL    |       |
| content     | text       | YES  |     | NULL    |       |
| length      | int(11)    | YES  |     | NULL    |       |
| authorship  | text       | YES  |     | NULL    |       |
| createdAt   | datetime   | NO   |     | NULL    |       |
| updatedAt   | datetime   | NO   |     | NULL    |       |
| noteId      | char(36)   | YES  |     | NULL    |       |
+-------------+------------+------+-----+---------+-------+
```

In fact , I have change TEXT to MediumText  to solve this. But I think there should be a solution to prevent this happen.
  Thanks!

**Comment by SISheogorath** [comment]
Are you running 1.1.0?

Because we changed all these text formats to long. While the default max note length of 10000 should be below this mark.

Can you please check you have the latest stable version and run the database migrations?

**Comment by ericma15** [comment]
First, my version is 1.1.0 .I found out that I didn't run the database migrations. Today I try to do this.But it throws a error:
```
  index: 0,
     sql: 'ALTER TABLE `Notes` ADD `shortid` VARCHAR(255) NOT NULL DEFAULT \'0000000000\';' },
  original:
   { Error: ER_DUP_FIELDNAME: Duplicate column name 'shortid'
       at Query.Sequence._packetToError (/var/www/md/node_modules/_mysql@2.15.0@mysql/lib/protocol/sequences/Sequence.js:52:14)
       at Query.ErrorPacket (/var/www/md/node_modules/_mysql@2.15.0@mysql/lib/protocol/sequences/Query.js:77:18)
       at Protocol._parsePacket (/var/www/md/node_modules/_mysql@2.15.0@mysql/lib/protocol/Protocol.js:279:23)
       at Parser.write (/var/www/md/node_modules/_mysql@2.15.0@mysql/lib/protocol/Parser.js:76:12)
       at Protocol.write (/var/www/md/node_modules/_mysql@2.15.0@mysql/lib/protocol/Protocol.js:39:16)
       at Socket.<anonymous> (/var/www/md/node_modules/_mysql@2.15.0@mysql/lib/Connection.js:103:28)
       at emitOne (events.js:115:13)
       at Socket.emit (events.js:210:7)
       at addChunk (_stream_readable.js:266:12)
       at readableAddChunk (_stream_readable.js:253:11)
       at Socket.Readable.push (_stream_readable.js:211:10)
       at TCP.onread (net.js:585:20)
       --------------------
       at Protocol._enqueue (/var/www/md/node_modules/_mysql@2.15.0@mysql/lib/protocol/Protocol.js:145:48)
       at Connection.query (/var/www/md/node_modules/_mysql@2.15.0@mysql/lib/Connection.js:208:25)
       at /var/www/md/node_modules/_sequelize@3.30.4@sequelize/lib/dialects/mysql/query.js:40:21
       at Promise._execute (/var/www/md/node_modules/_bluebird@3.5.1@bluebird/js/release/debuggability.js:303:9)
       at Promise._resolveFromExecutor (/var/www/md/node_modules/_bluebird@3.5.1@bluebird/js/release/promise.js:483:18)
       at new Promise (/var/www/md/node_modules/_bluebird@3.5.1@bluebird/js/release/promise.js:79:10)
       at Query.run (/var/www/md/node_modules/_sequelize@3.30.4@sequelize/lib/dialects/mysql/query.js:39:17)
       at /var/www/md/node_modules/_sequelize@3.30.4@sequelize/lib/sequelize.js:849:20
       at /var/www/md/node_modules/_retry-as-promised@2.3.1@retry-as-promised/index.js:39:21
       at Promise._execute (/var/www/md/node_modules/_bluebird@3.5.1@bluebird/js/release/debuggability.js:303:9)
       at Promise._resolveFromExecutor (/var/www/md/node_modules/_bluebird@3.5.1@bluebird/js/release/promise.js:483:18)
       at new Promise (/var/www/md/node_modules/_bluebird@3.5.1@bluebird/js/release/promise.js:79:10)
       at retryAsPromised (/var/www/md/node_modules/_retry-as-promised@2.3.1@retry-as-promised/index.js:29:10)
       at /var/www/md/node_modules/_sequelize@3.30.4@sequelize/lib/sequelize.js:848:12
       at tryCatcher (/var/www/md/node_modules/_bluebird@3.5.1@bluebird/js/release/util.js:16:23)
       at Promise._settlePromiseFromHandler (/var/www/md/node_modules/_bluebird@3.5.1@bluebird/js/release/promise.js:512:31)
     code: 'ER_DUP_FIELDNAME',
     errno: 1060,
     sqlMessage: 'Duplicate column name \'shortid\'',
     sqlState: '42S21',
     index: 0,
     sql: 'ALTER TABLE `Notes` ADD `shortid` VARCHAR(255) NOT NULL DEFAULT \'0000000000\';' },
  sql: 'ALTER TABLE `Notes` ADD `shortid` VARCHAR(255) NOT NULL DEFAULT \'0000000000\';' }

```
then I found the tables have been add the column shortid.  But I still find some field type is still text. Is this Ok? BTW, some of my Notes is 50239. Maybe this cause the problem.
```
+-------------+------------+------+-----+---------+-------+
| Field       | Type       | Null | Key | Default | Extra |
+-------------+------------+------+-----+---------+-------+
| id          | char(36)   | NO   | PRI | NULL    |       |
| patch       | mediumtext | YES  |     | NULL    |       |
| lastContent | text       | YES  |     | NULL    |       |
| content     | mediumtext | YES  |     | NULL    |       |
| length      | int(11)    | YES  |     | NULL    |       |
| authorship  | text       | YES  |     | NULL    |       |
| createdAt   | datetime   | NO   |     | NULL    |       |
| updatedAt   | datetime   | NO   |     | NULL    |       |
| noteId      | char(36)   | YES  |     | NULL    |       |
+-------------+------------+------+-----+---------+-------+

```
The patch and content field is modified by myself. It looks like database migrations only work a half.

**Comment by SISheogorath** [comment]
Eww… That's not good. (And the reason why our docker image runs the migrations before every start)

The probably easiest way to fix this mess is dumping your data with `mysqldump --no-create-info`, start with a new, empty db. run the migrations, reimport the data, then start HackMD.

Also I have to correct myself, I lost a 0 in my statement ^^ The default document length limit is 100000 not 10000.

By the way, the reason why the migrations fail is because also HackMD itself tries to sync the database schema. This works when you stay on one version forever but not when you ever want to update. And migrations itself check for their own data and notice what state they were used up to last time and try to continue there. If they start from scratch, the of course fail for safety when columns already exist and similar.

**Comment by ericma15** [comment]
Thanks! Now I modify the database manually. It works well now. Next time error occurs, I'll do what you say above.
