### ISSUE TITLE
DB socket connexion isn't supported

### ISSUE THREAD

**Issue by matunixe** [hackmdio/hackmd#99]
Hello !

Sorry to come back again but the implemented version of Sequelizejs doesn't support socket connexion for MySQL/MariaDB. Maybe someone know how to deal with this ?

I take a look at : http://docs.sequelizejs.com/en/1.7.0/docs/usage/ but in fact I'm really no a Js expert, I tried some modifications  in hackmd/node_modules/sequelize/lib/dialects/mysql/connection-manager.js but that doesn't work.

Thanks !

**Comment by jackycute** [comment]
Oh, it's ok.
But what do you mean socket connection for MySQL/MariaDB?
I've tried MySQL in my local machine, it works good to me.

Did you change the config.json for your MySQL settings?
You have to specify the `NODE_ENV` environment or it will auto use the `development` config.

Could you paste your error logs for further debug?

**Comment by matunixe** [comment]
Hello,

There it is.
**config.json**
```
{
    "development": {
        "domain": "localhost",
        "db": {
            "username": "umd",
            "password": "UnixcornMd",
            "database": "umd",
            "socket": "/var/run/mysqld/mysqld.sock",
            "dialect": "mysql"
        }
    },
    "production": {
        "domain": "md.unixcorn.org",
        "db": {
            "username": "umd",
            "password": "UnixcornMd",
            "database": "umd",
            "socket": "/var/run/mysqld/mysqld.sock",
            "dialect": "mysql"
        },
        "facebook": {
            "clientID": "change this",
            "clientSecret": "change this"
        },
        "twitter": {
            "consumerKey": "change this",
            "consumerSecret": "change this"
        },
        "github": {
            "clientID": "change this",
            "clientSecret": "change this"
        },
        "dropbox": {
            "clientID": "change this",
            "clientSecret": "change this"
        },
        "imgur": {
            "clientID": "change this"
        }
    }
}
```

First lines of **common.js**
```
//common
var domain = 'md.unixcorn.org'; // domain name
var urlpath = ''; // sub url path, like: www.example.com/<urlpath>
//settings
var debug = false;
```

The socketPath line added in hackmd/node_modules/sequelize/lib/dialects/mysql/**connection-manager.js**
```
ConnectionManager.prototype.connect = function(config) {
  var self = this;
  return new Promise(function (resolve, reject) {
    var connectionConfig = {
      host: config.host,
      port: config.port,
      socketPath: config.socket,
      user: config.username,
      password: config.password,
      database: config.database,
      timezone: self.sequelize.options.timezone,
      typeCast: ConnectionManager.$typecast.bind(self)
    };
```

I tried to start the server with the following command:
```
NODE_ENV=production node app.js
```

And there is the message returned:
```
Unhandled rejection SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:3306
    at Handshake._callback (/data/vhosts/md.unixcorn.org/hackmd/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:77:20)
    at Handshake.Sequence.end (/data/vhosts/md.unixcorn.org/hackmd/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Protocol.handleNetworkError (/data/vhosts/md.unixcorn.org/hackmd/node_modules/mysql/lib/protocol/Protocol.js:364:14)
    at Connection._handleNetworkError (/data/vhosts/md.unixcorn.org/hackmd/node_modules/mysql/lib/Connection.js:421:18)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at emitErrorNT (net.js:1249:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

Hope this help.
Thanks

**Comment by jackycute** [comment]
OK, I get it.

You DON'T need to modify sequelize, it already supported connect via socket.
Look at the `dialectOptions` in the [sequelize doc](http://docs.sequelizejs.com/en/1.7.0/docs/usage/), pass the options like below:
```js
// you can also pass any dialect options to the underlying dialect library
// - default is empty
// - currently supported: 'mysql', 'mariadb'
"dialectOptions": {
  "socketPath": "/Applications/MAMP/tmp/mysql/mysql.sock",
  "supportBigNumbers": true,
  "bigNumberStrings": true
},
```

So you only need to add `dialectOptions` under the db option in the `config.json`.
And everything should works fine.

**Comment by matunixe** [comment]
Thanks for your fast reply.

I put sequelize configuration back and modify `config.json` like this (just showing interesting parts):
```
"production": {
        "domain": "md.unixcorn.org",
        "db": {
            "username": "umd",
            "password": "UnixcornMd",
            "database": "umd",
            "dialectOptions": "/var/run/mysqld/mysqld.sock",
            "dialect": "mysql"
        },
```

Errors are still here:
```
Unhandled rejection SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:3306
    at Handshake._callback (/data/vhosts/md.unixcorn.org/hackmd/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:76:20)
    at Handshake.Sequence.end (/data/vhosts/md.unixcorn.org/hackmd/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Protocol.handleNetworkError (/data/vhosts/md.unixcorn.org/hackmd/node_modules/mysql/lib/protocol/Protocol.js:364:14)
    at Connection._handleNetworkError (/data/vhosts/md.unixcorn.org/hackmd/node_modules/mysql/lib/Connection.js:421:18)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at emitErrorNT (net.js:1249:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

What am I doing wrong?
